FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libdb-dev bison flex pkg-config

COPY . /repo
WORKDIR /repo
RUN ./configure
RUN make -j8 

RUN mkdir -p /deps
RUN ldd /repo/ip/ip | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:22.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /repo/ip/ip /repo/ip/ip
ENV LD_LIBRARY_PATH=/deps
